package it.univr.neuralnetworks;


import java.util.Arrays;


import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.learning.config.Adam;
import org.nd4j.linalg.lossfunctions.LossFunctions.LossFunction;

import it.univr.cevprices.CevPrices;

/**
 * This class uses the libraries deeplearning4j and nd4j in order to create and train a neural network which has to learn if
 * an underlying process has a financial bubble or not based on the call prices it generates. 
 * In particular, here we consider processes X^i=(X^i_t)_{t >= 0} following the dynamics
 *   
 * dX^i_t = sigma*(X^i_t)^(beta_i)dB_t^i  (1)
 * X_0 = x_0.
 * 
 * These are CEV models, and they have a bubble if and only if beta_i>1. In this example, we have sigma = 0.3 and x_0=2.
 * 
 * The call prices generated by this model can be computed analytically, and we do that in the class it.univr.cevprices.CevPrices.
 * We take 30 equally-spaced strikes between 1.0 and 3.0, and 50 equally-spaced maturities from 0.5 to 2.0.  
 * 
 * With these data, we train a neural network with 2 hidden layers of 50 and 20 nodes, respectively, giving it prices generated
 * in half cases by true martingale and in half cases by strict local martingales. We compute the weights and the biases via the
 * Adam algorithm with learning rate equal to 0.01 and 20 epochs. 
 * 
 * We then test it for prices generated by processes following (1) with other exponents. 
 * 
 * @author Andrea Mazzon
 *
 */
public class NeuralNetworksForBubbleDetection {

	public static void main(String[] args) {
			
		//CONSTRUCTION OF THE NETWORK
		
		//parameters
		
		double learningRate = 0.01;
		int numberOfStrikes = 30;
		int numberOfMaturities = 50;
		int numberOfNodesOfFirstHiddenLayer = 50;
		int numberOfNodesOfSecondHiddenLayer = 20;
		
		MultiLayerConfiguration layersConstruction = new NeuralNetConfiguration.Builder()
				.updater(new Adam(learningRate))//we specify how we want to update the optimal coefficients
				.list()//now we want to specify the connections between the layers 
				//the following is the connection between input layer and first hidden layer:
				.layer(new DenseLayer.Builder()
						.nIn(numberOfStrikes*numberOfMaturities)//this is the number of inputs it receives
						.nOut(numberOfNodesOfFirstHiddenLayer)//this is the number of outputs: nodes of first hidden layer
						.activation(Activation.RELU)//it has ReLU activation function
						.build())
				//the following is the connection between first hidden layer and second hidden layer:
				.layer(new DenseLayer.Builder()
						.nIn(numberOfNodesOfFirstHiddenLayer)
						.nOut(numberOfNodesOfSecondHiddenLayer)
						.activation(Activation.RELU)
						.build())
				//the following is the connection between the second hidden layer and the output layer:
				.layer(new OutputLayer.Builder()//we have to specify that it is and output layer
						.nIn(numberOfNodesOfSecondHiddenLayer)
						.nOut(1)
						/*
						 * It has sigmoid activation function: it means that it outputs a number that we can interpret as the
						 * probability that the input prices are generated by a bubble
						 */
						.activation(Activation.SIGMOID)
						.lossFunction(LossFunction.XENT)//XENT is the binary cross-entropy loss function, commonly used for binary classification
						.build())
				.build();
		
		//we construct a neural network out of these layers..
		MultiLayerNetwork ourNetwork = new MultiLayerNetwork(layersConstruction);
		
		//..and we make it ready to be trained
		ourNetwork.init();
		
		//BUILDING OF TRAINING SET
		
		double initialValueUnderlying = 2.0;
		double sigmaUnderlying = 0.3;
		
		//generation of strikes and maturities
		
		double smallestStrike = 1.0;
		double biggestStrike = 3.0;
		
		double smallestMaturity = 0.5; 
		double biggestMaturity = 2.0;
		
		double[] strikes = new double[numberOfStrikes];
		double[] maturities = new double[numberOfMaturities];
		
		double strikeStep = (biggestStrike-smallestStrike)/(numberOfStrikes-1);
		
		for (int i = 0; i<numberOfStrikes; i++) {
			strikes[i]=smallestStrike+strikeStep*i;
		}
		
		double maturityStep = (biggestMaturity-smallestMaturity)/(numberOfMaturities-1);
		
		for (int i = 0; i<numberOfMaturities; i++) {
			maturities[i]=smallestMaturity+maturityStep*i;
		}
		

		int numberOfBubblesForTraining = 40; 
		int numberOfNonBubblesForTraining = 40;
		
		//rows are prices generated by a given exponent, for all combinations of strikes and maturities
		double[][] callPricesForTraining =
				new double[numberOfBubblesForTraining+numberOfNonBubblesForTraining]
						[numberOfStrikes*numberOfMaturities];

		double smallestExponentForBubbles = 1.01;
		double biggestExponentForBubbles = 1.5;
		
		double smallestExponentForNonBubbles = 0.5;
		double biggestExponentForNonBubbles = 0.99;	
		
		double[] exponentsForBubbles = 
				new double[numberOfBubblesForTraining];
	
		double exponentsForBubbleStep =
				(biggestExponentForBubbles-smallestExponentForBubbles)/(numberOfBubblesForTraining-1);
		
		for (int i = 0; i<numberOfBubblesForTraining; i++) {
			exponentsForBubbles[i]=smallestExponentForBubbles+exponentsForBubbleStep*i;
		}
		
		double[] exponentsForNonBubbles = new double[numberOfNonBubblesForTraining];
		
		double exponentsForNonBubbleStep =
				(biggestExponentForNonBubbles-smallestExponentForNonBubbles)/(numberOfNonBubblesForTraining-1);
	
		for (int i = 0; i<numberOfNonBubblesForTraining; i++) {
			exponentsForNonBubbles[i]=smallestExponentForNonBubbles+exponentsForNonBubbleStep*i;
		}
		
		//all beta_i > 1
		for (int i = 0; i < numberOfBubblesForTraining;i++) {
			double exponent = exponentsForBubbles[i];
			for (int j = 0; j < numberOfMaturities; j++) {
				double maturity = maturities [j];
				for (int k = 0; k < numberOfStrikes; k++) {
					double strike = strikes[k]; 
					double callPrice =
							CevPrices.CEVPriceCallForExponentBiggerThanOne(
									initialValueUnderlying,
									sigmaUnderlying,
									exponent,
									maturity,
									strike);
					callPricesForTraining[i][j*numberOfStrikes+k] = callPrice; 
				}
			}
		}
		
		//all beta_i <= 1
		for (int i = numberOfBubblesForTraining;
				i < numberOfBubblesForTraining+numberOfNonBubblesForTraining;i++) {
			double exponent = exponentsForNonBubbles[i-numberOfBubblesForTraining];
			for (int j = 0; j < numberOfMaturities; j++) {
				double maturity = maturities[j];
				for (int k = 0; k < numberOfStrikes; k++) {
					double strike = strikes[k]; 
					double callPrice =
							CevPrices.CEVPriceCallForExponentSmallerEqualOne(
									initialValueUnderlying,
									sigmaUnderlying,
									exponent,
									maturity,
									strike);
					callPricesForTraining[i][j*numberOfStrikes+k] = callPrice; 
				}
			}
		}
		
		/*
		 * They will be 1 for bubbles, 0 for non-bubbles. So we hope that the network
		 * "learns the rule" that associates prices to these labels. We define it as a
		 * matrix with only one column to make it compatible with the output of the network 
		 */
		double[][] labelsForTraining =
				new double[numberOfBubblesForTraining+numberOfNonBubblesForTraining][1];
		
		for (int i = 0; i < numberOfBubblesForTraining;i++) {
			labelsForTraining[i][0]=1;
		}
		
		for (int i = numberOfBubblesForTraining;
				i < numberOfBubblesForTraining+numberOfNonBubblesForTraining;i++) {
			labelsForTraining[i][0]=0;
		}
		
		//we transform the two matrices in objects that can be used to create a DataSet to train the network that we construct below
		INDArray pricesDataForTraining = Nd4j.create(callPricesForTraining);
		INDArray labelsDataForTraining = Nd4j.create(labelsForTraining);
		
		DataSet trainingData = new DataSet(pricesDataForTraining, labelsDataForTraining);
		
		//TRAINING OF THE NETWORK
		int numberOfEpochs = 20;
		
		for (int epochIndex = 0; epochIndex<numberOfEpochs; epochIndex++) {
			//training step for the current epoch
			ourNetwork.fit(trainingData);
		}
		
		//construction of the test data
		
		int numberOfBubblesForTesting = 10; 
		int numberOfNonBubblesForTesting = 10;
		
		double[][] callPricesForTesting =
				new double[numberOfBubblesForTesting+numberOfNonBubblesForTesting]
						[numberOfStrikes*numberOfMaturities];

		double smallestExponentForBubblesTest = 1.01;
		double biggestExponentForBubblesTest = 1.15;
		
		double smallestExponentForNonBubblesTest = 0.85;
		double biggestExponentForNonBubblesTest = 0.99;	
		
		double[] exponentsForBubblesTest = 
				new double[numberOfBubblesForTesting];
	
		double exponentsForBubbleStepTest =
				(biggestExponentForBubblesTest-smallestExponentForBubblesTest)
				/(numberOfBubblesForTesting-1);
		
		for (int i = 0; i<numberOfBubblesForTesting; i++) {
			exponentsForBubblesTest[i]=smallestExponentForBubblesTest
					+exponentsForBubbleStepTest*i;
		}
		
		double[] exponentsForNonBubblesTest = 
				new double[numberOfNonBubblesForTesting];
		
		double exponentsForNonBubbleStepTest =
				(biggestExponentForNonBubblesTest-smallestExponentForNonBubblesTest)
				/(numberOfNonBubblesForTesting-1);
	
		for (int i = 0; i<numberOfNonBubblesForTesting; i++) {
			exponentsForNonBubblesTest[i]=smallestExponentForNonBubblesTest
					+exponentsForNonBubbleStepTest*i;
		}
		
		//all beta_i > 1
		for (int i = 0; i < numberOfBubblesForTesting;i++) {
			double exponent = exponentsForBubblesTest[i];
			for (int j = 0; j < numberOfMaturities; j++) {
				double maturity = maturities [j];
				for (int k = 0; k < numberOfStrikes; k++) {
					double strike = strikes[k]; 
					double callPrice =
							CevPrices.CEVPriceCallForExponentBiggerThanOne(
									initialValueUnderlying,
									sigmaUnderlying,
									exponent,
									maturity,
									strike);
					callPricesForTesting[i][j*numberOfStrikes+k] = callPrice; 
				}
			}
		}
		
		//all beta_i <= 1
		for (int i = numberOfBubblesForTesting;
				i < numberOfBubblesForTesting+numberOfNonBubblesForTesting;i++) {
			double exponent = exponentsForNonBubblesTest[i-numberOfBubblesForTesting];
			for (int j = 0; j < numberOfMaturities; j++) {
				double maturity = maturities [j];
				for (int k = 0; k < numberOfStrikes; k++) {
					double strike = strikes[k]; 
					double callPrice =
							CevPrices.CEVPriceCallForExponentSmallerEqualOne(
									initialValueUnderlying,
									sigmaUnderlying,
									exponent,
									maturity,
									strike);
					callPricesForTesting[i][j*numberOfStrikes+k] = callPrice; 
				}
			}
		}

		
		INDArray pricesDataForTesting = Nd4j.create(callPricesForTesting);
		
		//we get the the predictions of the network..
		INDArray networkPredictions = ourNetwork.output(pricesDataForTesting);
		
		//..and transform them into a double array
		double[] networkPredictionsAsArray = networkPredictions.toDoubleVector();
		
		System.out.println("Probabilities that the underlyings for testing are bubbles");
		System.out.println(Arrays.toString(networkPredictionsAsArray));
		
	}

}
