package it.univr.neuralnetworks;


import java.util.Arrays;
import java.util.Random;

import org.deeplearning4j.nn.conf.MultiLayerConfiguration;
import org.deeplearning4j.nn.conf.NeuralNetConfiguration;
import org.deeplearning4j.nn.conf.layers.DenseLayer;
import org.deeplearning4j.nn.conf.layers.OutputLayer;
import org.deeplearning4j.nn.multilayer.MultiLayerNetwork;
import org.nd4j.linalg.activations.Activation;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.dataset.DataSet;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.linalg.learning.config.Adam;
import org.nd4j.linalg.lossfunctions.LossFunctions.LossFunction;

import it.univr.cevprices.CevPrices;

/**
 * This class uses the libraries deeplearning4j and nd4j in order to create and train a neural network which has to learn if
 * an underlying process has a financial bubble or not based on the call prices it generates. 
 * In particular, here we consider processes X^i=(X^i_t)_{t >= 0} following the dynamics
 *   
 * dX^i_t = (X^i_t)^(beta_i)dB_t^i,  (1)
 * X_0 = x_0,
 * 
 * where beta_i are random variables, uniformly distributed in and [0.5, 1.5]. These are CEV
 * models, and they have a bubble if and only if beta_i>1. In this example, we have sigma = 1.0 and x_0=2.
 * 
 * The call prices generated by this model can be computed analytically, and we do that in the class it.univr.cevprices.CevPrices.
 * We take 30 equally-spaced strikes between 0.5 and 10, and 50 equally-spaced maturities from 0.1 to 1.5.  
 * 
 * With these data, we train a neural network with 2 hidden layers of 200 and 100 nodes, respectively, giving it prices generated
 * in half cases by true martingale and in half cases by strict local martingales. We compute the weights and the biases via the
 * Adam algorithm with learning rate equal to 0.001 and 30 epochs. 
 * 
 * We then test it for prices generated by processes following (1) with other displacements and exponents. 
 * 
 * @author Andrea Mazzon
 *
 */
public class NeuralNetworksForBubbleDetection {

	public static void main(String[] args) {
			
	
	}

}
